### ISSUE TITLE
xxe

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/ibm-cos-sdk-java#20]
HI！
I found that there are many places in ibm-cos-sdk-java that handle xml without disabling xml external entities, which may lead to xml external entity injection vulnerability.Take XmlUtil.java as an example：
![图片](https://user-images.githubusercontent.com/39950310/56205262-d908fe80-607b-11e9-9dd5-df0a5e3922dc.png)
The same problem still exists elsewhere：
parseRegionMetadata.java  lline 118 ;
XpathUtils.java  line 116;
parseXmlInputStream.java  line 142;

**Comment by barry-hueston-IBM** [comment]
Internal ticket reference: CSAFE-54086

**Comment by smcgrath-IBM** [comment]
@360CodeSafe how are you analysing the code? I see an issue within XpathUtils.java which needs patched and the related classes which use it. Howevere parseRegionMetadata & parseXmlInputStream are more difficult to determine

**Comment by 360CodeSafe** [comment]
We use the internal static code auditing tool (Qianxin Code Guardian) to do static code analysis and then manually review it.

The following is the data flow of our engine analysis：
1.parseRegionMetadata.java:
![图片](https://user-images.githubusercontent.com/39950310/57742649-95de9180-76f4-11e9-9c58-84bf58f0300e.png)
![图片](https://user-images.githubusercontent.com/39950310/57742658-a262ea00-76f4-11e9-8160-10ded331b81a.png)
2.parseResponseSaxParser.java(Sorry, I may have made a mistake before.)
![图片](https://user-images.githubusercontent.com/39950310/57742778-11404300-76f5-11e9-9bc6-84cba1b72ec7.png)

Because I don’t know much about the project, whether the input point is controlled by the attacker needs the developer’s own judgment.

**Comment by barry-hueston-IBM** [comment]
@QiAnXinCodeSafe  this issue has been resolved in the latest release of the SDK, version 2.5.0. Please review and let us know if this issue can be closed.
