### ISSUE TITLE
SAST: ErrorHandling.RevealDetails.StackTrace

### ISSUE THREAD

**Issue by roryodonnell** [IBM/ibm-cos-sdk-java#50]
https://github.com/IBM/ibm-cos-sdk-java/blob/79bae8197ddfbe90b63112a2944864e4dcaefc23/ibm-cos-java-sdk-s3/src/main/java/com/ibm/cloud/objectstorage/services/s3/AmazonS3Client.java#L4522

*Existing*
```
            /**
             * Wrap OAuthServiceException as AmazonS3Exception and re-throw for backwards compatability.
             */
            AmazonS3Exception ase = new AmazonS3Exception(ose.getErrorMessage());
            ase.setStatusCode(ose.getStatusCode());
            ase.setServiceName("IAM");
            ase.setStackTrace(ose.getStackTrace());
            throw ase;
```

*Possible solution*
```
            /**
             * Wrap OAuthServiceException as AmazonS3Exception and re-throw for backwards compatability.
             */
            AmazonS3Exception ase = new AmazonS3Exception(ose.getErrorMessage(), ose);
            ase.setStatusCode(ose.getStatusCode());
            ase.setServiceName("IAM");
            throw ase;
```

![image](https://user-images.githubusercontent.com/26009048/151019207-ba5402d3-d7bc-4b80-a11c-89a335ea8d75.png)

**Comment by IBMeric** [comment]
As the code states, one exception is being wrapped and re-thrown as another. The stack trace for the new exception needs to match the original, which requires using that value.

The scanner probably flags this because it is not good practice to display stack trace details to end users. However, the SDK is a framework for building applications, and much like a development library, is not the final link in the chain. The end application is responsible for properly sanitizing details displayed to users.

**Comment by roryodonnell** [comment]
Thanks Eric -
