### ISSUE TITLE
TransferManager. uploadDirectory not uploading empty directories.

### ISSUE THREAD

**Issue by carlosperri** [IBM/ibm-cos-sdk-java#59]
I'm trying to upload a list of directories from my local to my COS bucket using TransferManager.

I noticed that **empty directories are not getting uploaded**, just directories with files inside are being uploaded to my COS bucket.
I'm using the below method with **includeSubdirectories = true.**
`uploadDirectory(String bucketName, String virtualDirectoryKeyPrefix, File directory, boolean includeSubdirectories) `

How to get all directories uploaded, including the empty ones?

Thanks.

**Comment by avinash1IBM** [comment]
Buckets and objects are the primary resources, and objects are stored in buckets. COS has a flat structure instead of a hierarchy like you would see in a file system. The folder concept you see in the console is a means of grouping objects. The console does this by using a shared name prefix for the grouped objects. In other words, the grouped objects have names that begin with a common string. This common string, or shared prefix, is the folder name. 

Coming to TransferManager, it checks for the files in a directory and if there are none, it can't be uploaded. Non empty directory can be uploaded
